parameters: {}
environment: {}
packages:
    - name: tasks
      shared: false
      environment:
        DB_HOST: "${DB_HOST}"
        DB_USERNAME: "${DB_USERNAME}"
        DB_PASSWORD: "${DB_PASSWORD}"
        DB_NAME: "${DB_NAME}"
      parameters: { }
      annotations: { }
      functions:
        - name: add
          binary: false
          main: ""
          runtime: python:3.11
          web: true
          webSecure: false
          parameters: { }
          environment: { }
          annotations: { }
          limits: { }
        - name: list
          binary: false
          main: ""
          runtime: python:3.11
          web: true
          webSecure: false
          parameters: { }
          environment: { }
          annotations: { }
          limits: { }
        - name: delete
          binary: false
          main: ""
          runtime: python:3.11
          web: true
          webSecure: false
          parameters: { }
          environment: { }
          annotations: { }
          limits: { }
        - name: update
          binary: false
          main: ""
          runtime: python:3.11
          web: true
          webSecure: false
          parameters: { }
          environment: { }
          annotations: { }
          limits: { }
